# Generated by Django 2.1.5 on 2019-02-02 10:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief summary of course', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='lectureInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Course lecture number', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('c', 'Closed'), ('a', 'Available'), ('w', 'WaitList')], default='m', help_text='Course availability', max_length=1)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cc.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Major (e.g. Computer Science)', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cc.Instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='major',
            field=models.ManyToManyField(help_text='Select a major of this course', to='cc.Major'),
        ),
    ]
