# Generated by Django 2.1.5 on 2019-02-02 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lectureInstance',
            new_name='CourseInstance',
        ),
    ]
