# Generated by Django 2.1.5 on 2019-02-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0003_courseinstance_regstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinstance',
            name='next_registration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
