# Generated by Django 2.1.5 on 2019-02-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0004_courseinstance_next_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinstance',
            name='summary',
            field=models.ManyToManyField(help_text='Select a major of this lecture', to='cc.Major'),
        ),
    ]
