# Generated by Django 2.1.5 on 2019-02-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0005_courseinstance_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinstance',
            name='summary',
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='summary',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
